Script enhancements (handle missing content and references)

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -1,25 +1,29 @@
 #!/bin/bash
 
 # Variables
-#   - Directories
+# - Directories
 content_dir="./content"
 chapters_dir="$content_dir/chapters"
 references_dir="$content_dir/references"
 scripts_dir="./scripts"
 pandoc_dir="$scripts_dir/pandoc"
 output_dir="./output"
-#   - Files
+# - Files
 template_file="$pandoc_dir/template.latex"
 tmp_file="$output_dir/.tmp"
 source_file=$tmp_file
 output_file="$output_dir/prejmenovat.pdf"
-#   - Colors
+# - Colors
 red_color='\033[0;31m'
+yellow_color='\033[0;33m'
 no_color='\033[0m' # No Color
 
-# Check if content directory exists
-if [ ! -d "$content_dir" ]; then
-  echo -e "${red_color}Error:${no_color} Content directory '$content_dir)' doesn't exist."
+# Check if chapters directory exists and contains at least one file
+if [ ! -d "$chapters_dir" ]; then
+  echo -e "${red_color}Error:${no_color} Chapters directory '$chapters_dir' doesn't exist."
+  exit 1
+elif [ `ls "$chapters_dir" | wc -l` == 0 ]; then
+  echo -e "${red_color}Error:${no_color} Chapters directory '$chapters_dir' is empty."
   exit 1
 fi
 
@@ -27,30 +31,39 @@ fi
 mkdir -p $output_dir
 
 # Merge all chapters into .tmp
-#   - For each file in directory
 for file in $chapters_dir/*;
 do
-#   - Insert contents into .tmp and add newline
   (cat "${file}"; echo;) >> $tmp_file
 done
 
-# Create reference files list
-#   a) Check if there are multiple files
-#   b) List all files in references directory
-#   c) Convert newlines to commas
-#   d) Remove trailing comma
-#   e) Convert commas to --bibliography
-count=`ls "$references_dir" | wc -l`
-if [ $count != 1 ]; then
-  references_files=$(find $references_dir/* | tr '\n' ',' | sed s'/,$//' | sed s'/,/ --bibliography /g')
+# Check that references directory exists and is not empty
+if [ ! -d "$references_dir" ]; then
+  bibliography=""
+  echo -e "${yellow_color}Warning:${no_color} References directory '$references_dir' doesn't exist."
+elif [ `ls "$references_dir" | wc -l` == 0 ]; then
+  bibliography=""
+  echo -e "${yellow_color}Warning:${no_color} References directory '$references_dir' is empty."
 else
-  references_files=$(find $references_dir/*)
+  # Create reference files list
+  # a) Check if there are multiple files
+  # b) List all files in references directory
+  # c) Convert newlines to commas
+  # d) Remove trailing comma
+  # e) Convert commas to --bibliography
+  # f) Prepend --bibliography
+  count=`ls "$references_dir" | wc -l`
+  if [ $count != 1 ]; then
+    references_files=$(find $references_dir/* | tr '\n' ',' | sed s'/,$//' | sed s'/,/ --bibliography /g')
+  elif [ $count = 1 ]; then
+    references_files=$(find $references_dir/*)
+  fi
+  bibliography="--bibliography "$references_files
 fi
 
 eval "pandoc -s\
   --template $template_file\
   --filter pandoc-citeproc\
-  --bibliography $references_files\
+  $bibliography\
   $source_file -o $output_file"
 
 # Clean
